@ToDoApp.API_HostAddress = http://localhost:5044


GET {{ToDoApp.API_HostAddress}}/ToDoService/GetToDos
Accept: application/json

###

POST {{ToDoApp.API_HostAddress}}/ToDoService/GetToDo
Accept: application/json
Content-Type: application/json
{
  "id": 1
}

###

POST {{ToDoApp.API_HostAddress}}/ToDoService/CreateToDo
Accept: application/json
Content-Type: application/json
{

  "name": "Test Posting a ToDo",
  "description": "Test that post works",
  "isCompleted": true

}
###

GET {{ToDoApp.API_HostAddress}}/ToDo/GetToDos
Accept: application/json
###

POST {{ToDoApp.API_HostAddress}}/ToDo/PostTodo
Accept: application/json
Content-Type: application/json
{
  "Name": "Repl SQL posted todo",
  "Description": "A todo posting to the SQL server",
  "IsCompleted": false,
  "StartDate": "2001/1/1",
  "EndDate": "2002/2/2"
}
###